"""Shared data models used across scanners, execution, and exchange access."""

from __future__ import annotations

from datetime import datetime, timezone
from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class Quote:
    """Best bid/ask snapshot for a market symbol."""
    symbol: str
    bid: float
    ask: float
    bid_size: float
    ask_size: float
    timestamp_ms: int | None = None


@dataclass(frozen=True)
class OrderIntent:
    """A normalized order plan generated by a strategy."""
    exchange: str
    symbol: str
    side: str
    price: float
    amount: float
    note: str = ""


@dataclass(frozen=True)
class Opportunity:
    """A detected arbitrage opportunity with expected edge and order plan."""
    strategy: str
    venue: str
    summary: str
    edge_bps: float
    expected_pnl: float
    pnl_currency: str
    orders: tuple[OrderIntent, ...] = ()
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class ExecutionRecord:
    """Normalized record of a paper or live execution attempt."""

    timestamp: str
    mode: str
    strategy: str
    venue: str
    summary: str
    status: str
    edge_bps: float
    expected_pnl: float
    pnl_currency: str
    order_count: int
    reason: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def now(
        cls,
        *,
        mode: str,
        strategy: str,
        venue: str,
        summary: str,
        status: str,
        edge_bps: float,
        expected_pnl: float,
        pnl_currency: str,
        order_count: int,
        reason: str = "",
        metadata: dict[str, Any] | None = None,
    ) -> "ExecutionRecord":
        """Construct an execution record with a UTC timestamp."""
        return cls(
            timestamp=datetime.now(timezone.utc).isoformat(),
            mode=mode,
            strategy=strategy,
            venue=venue,
            summary=summary,
            status=status,
            edge_bps=edge_bps,
            expected_pnl=expected_pnl,
            pnl_currency=pnl_currency,
            order_count=order_count,
            reason=reason,
            metadata=metadata or {},
        )


@dataclass(frozen=True)
class BalanceSnapshot:
    """One timestamped balance snapshot for a specific exchange."""

    exchange: str
    timestamp: str
    balances: dict[str, float]

    @classmethod
    def now(cls, exchange: str, balances: dict[str, float]) -> "BalanceSnapshot":
        """Construct a balance snapshot with a UTC timestamp."""
        return cls(
            exchange=exchange,
            timestamp=datetime.now(timezone.utc).isoformat(),
            balances=balances,
        )


@dataclass(frozen=True)
class ErrorRecord:
    """Timestamped runtime error record kept for operator visibility."""

    timestamp: str
    source: str
    message: str

    @classmethod
    def now(cls, source: str, message: str) -> "ErrorRecord":
        """Construct an error record with a UTC timestamp."""
        return cls(
            timestamp=datetime.now(timezone.utc).isoformat(),
            source=source,
            message=message,
        )


@dataclass(frozen=True)
class OrderStatusRecord:
    """Tracked lifecycle state for one submitted exchange order."""

    exchange: str
    symbol: str
    order_id: str
    side: str
    amount: float
    price: float
    status: str
    filled: float
    remaining: float
    timestamp: str
    raw: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class FillRecord:
    """Normalized fill/trade record derived from exchange order/trade responses."""

    exchange: str
    symbol: str
    order_id: str
    side: str
    filled: float
    average_price: float
    fee_cost: float
    fee_currency: str
    timestamp: str
    raw: dict[str, Any] = field(default_factory=dict)
